sudo: false
language: java
jdk: oraclejdk13
dist: trusty
cache:
    apt: true
    directories:
        - $HOME/.m2
env:
  - GTK=3.24
script: mvn clean verify
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
